/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package demo.dummyagent;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int listitem_received_msg=0x7f040000;
        public static final int listitem_receivers_text_color=0x7f040002;
        public static final int listitem_sent_msg=0x7f040001;
    }
    public static final class drawable {
        public static final int contact_32=0x7f020000;
        public static final int downmod=0x7f020001;
        public static final int dummyagent=0x7f020002;
        public static final int jade=0x7f020003;
        public static final int msg=0x7f020004;
        public static final int runtree=0x7f020005;
        public static final int scrollbar_vertical_thumb=0x7f020006;
        public static final int scrollbar_vertical_track=0x7f020007;
        public static final int upmod=0x7f020008;
    }
    public static final class id {
        public static final int addressEdit=0x7f060005;
        public static final int addressTxt=0x7f060004;
        public static final int agentNameEdit=0x7f060003;
        public static final int agentNameTxtView=0x7f060000;
        public static final int cancelBtn=0x7f060008;
        public static final int checkFullName=0x7f060002;
        public static final int clearbtn=0x7f06001c;
        public static final int comActDet=0x7f06000e;
        public static final int commAct=0x7f060018;
        public static final int commActTxtView=0x7f060017;
        public static final int content=0x7f06001a;
        public static final int content1=0x7f060001;
        public static final int content2=0x7f060006;
        public static final int contentDet=0x7f060010;
        public static final int messageList=0x7f06001d;
        public static final int okBtn=0x7f060007;
        public static final int receiverList=0x7f060016;
        public static final int receiverListDet=0x7f06000c;
        public static final int receiverTxtView=0x7f060015;
        public static final int replyBtnDet=0x7f060011;
        public static final int sendBtn=0x7f06001b;
        public static final int sender=0x7f060014;
        public static final int senderDet=0x7f06000a;
        public static final int senderTxtView=0x7f060013;
        public static final int tabs=0x7f060012;
        public static final int widget26Det=0x7f060009;
        public static final int widget28Det=0x7f06000b;
        public static final int widget30Det=0x7f06000d;
        public static final int widget41=0x7f060019;
        public static final int widget4Det1=0x7f06000f;
    }
    public static final class layout {
        public static final int dialog_message=0x7f030000;
        public static final int message_details=0x7f030001;
        public static final int send_message=0x7f030002;
    }
    public static final class string {
        public static final int activity_local_jade_controller=0x7f050002;
        public static final int app_name=0x7f050003;
        public static final int close=0x7f050012;
        public static final int confirm=0x7f050011;
        public static final int content=0x7f050010;
        /**  DIALOG PROPERTIES 
         */
        public static final int dialog_title=0x7f050007;
        public static final int error_msg_connect=0x7f05000a;
        /**   ERROR MESSAGES 
         */
        public static final int error_msg_empty_aid=0x7f050008;
        public static final int error_msg_generic=0x7f05000b;
        public static final int error_msg_stale_proxy=0x7f050009;
        /**  JADE CONNECTION PROPERTIES 
         */
        public static final int host=0x7f050013;
        /**  CONTEXT MENU ITEMS 
         */
        public static final int menu_item_add=0x7f050016;
        public static final int menu_item_edit=0x7f050017;
        public static final int menu_item_exit=0x7f05000c;
        public static final int menu_item_remove=0x7f050018;
        public static final int menu_item_removeall=0x7f050019;
        public static final int msg_details=0x7f050006;
        public static final int msisdn=0x7f050015;
        public static final int notify_msg_received=0x7f05000e;
        public static final int port=0x7f050014;
        public static final int receiver=0x7f05000f;
        public static final int recv_msg_tab_indicator=0x7f050001;
        public static final int send_and_recv_message=0x7f050005;
        public static final int send_message=0x7f050004;
        public static final int send_msg_tab_indicator=0x7f050000;
        public static final int statusbar_msg_connected=0x7f05000d;
    }
}
